export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const SET_EVENTS = 'SET_EVENTS'
//export const REMOVE_EVENTS = 'REMOVE_EVENTS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const SUBMIT_ORDER = 'SUBMIT_ORDER'